In [6]:
import torch

torch.__version__

'2.0.1'

## Tensor

In [13]:
x = torch.tensor([[0, 1, 1], [1, 1, 0], [0, 0, 1]])

In [14]:
x

tensor([[0, 1, 1],
        [1, 1, 0],
        [0, 0, 1]])

In [17]:
x[1][1]

tensor(1)

In [18]:
torch.zeros(1,4)

tensor([[0., 0., 0., 0.]])

In [19]:
torch.ones(3, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
torch.ones(1, 2) + torch.ones(1, 2)

tensor([[2., 2.]])

In [23]:
torch.ones(1).item()

1.0

In [25]:
x.device

device(type='cpu')

In [28]:
x.to("mps")

tensor([[0, 1, 1],
        [1, 1, 0],
        [0, 0, 1]], device='mps:0')

In [29]:
x.device

device(type='cpu')

In [30]:
import torch
import torchvision

device = torch.device("mps")

x = torch.randn(128, 128, device=device)
net = torchvision.models.resnet18().to(device)

print(x.device)
print(next(net.parameters()).device)

mps:0
mps:0


In [31]:
x.device

device(type='mps', index=0)

In [32]:
tensor1 = torch.ones(1, 4)

In [33]:
tensor1.device

device(type='cpu')

In [34]:
tensor2 = tensor1.to("mps")

In [35]:
tensor2.device

device(type='mps', index=0)

In [36]:
tensor1.device

device(type='cpu')

In [37]:
tensor1 = tensor1.to("mps")

In [38]:
tensor1.device

device(type='mps', index=0)

In [39]:
torch.rand(2, 5).max()

tensor(0.9616)

In [40]:
torch.rand(4, 5).max().item()

0.9917497634887695

In [41]:
long_tensor = torch.tensor([[1,3,4],[1,5,8]])

In [42]:
long_tensor.type()

'torch.LongTensor'

In [43]:
float_tensor = long_tensor.to(dtype=torch.float32)

In [44]:
float_tensor.type()

'torch.FloatTensor'

In [45]:
long_tensor.type()

'torch.LongTensor'

In [51]:
random_tensor = torch.rand(3,5)

In [52]:
random_tensor.log2()

tensor([[-0.3473, -1.3022, -0.5300, -1.0883, -4.0459],
        [-5.1297, -2.1162, -0.0705, -0.1084, -0.0410],
        [-0.3842, -1.4766, -5.2787, -3.0243, -0.8858]])

In [54]:
random_tensor.log2_()

tensor([[-0.3473, -1.3022, -0.5300, -1.0883, -4.0459],
        [-5.1297, -2.1162, -0.0705, -0.1084, -0.0410],
        [-0.3842, -1.4766, -5.2787, -3.0243, -0.8858]])

In [55]:
random_tensor

tensor([[-0.3473, -1.3022, -0.5300, -1.0883, -4.0459],
        [-5.1297, -2.1162, -0.0705, -0.1084, -0.0410],
        [-0.3842, -1.4766, -5.2787, -3.0243, -0.8858]])

In [58]:
flat_tensor = torch.rand(784)

In [59]:
flat_tensor

tensor([0.8191, 0.9916, 0.5209, 0.2879, 0.0177, 0.2803, 0.4463, 0.6851, 0.8156,
        0.1780, 0.7343, 0.4050, 0.6385, 0.4054, 0.3816, 0.4684, 0.8711, 0.2904,
        0.5789, 0.1956, 0.1472, 0.9739, 0.6569, 0.1424, 0.5602, 0.7926, 0.3876,
        0.7309, 0.5363, 0.7460, 0.3407, 0.3454, 0.8003, 0.4253, 0.0520, 0.0832,
        0.0115, 0.0671, 0.4216, 0.5344, 0.4158, 0.5167, 0.4873, 0.1491, 0.2955,
        0.2971, 0.3039, 0.7933, 0.2146, 0.1115, 0.8082, 0.2362, 0.2028, 0.4058,
        0.0821, 0.0465, 0.1979, 0.1524, 0.8453, 0.0904, 0.1959, 0.5105, 0.3034,
        0.5521, 0.9853, 0.0066, 0.7204, 0.0786, 0.8199, 0.1880, 0.6227, 0.9084,
        0.6951, 0.6598, 0.0698, 0.1882, 0.0908, 0.8478, 0.0016, 0.9027, 0.7384,
        0.3312, 0.7310, 0.5466, 0.2224, 0.0580, 0.6250, 0.7266, 0.8384, 0.1095,
        0.1944, 0.1168, 0.9443, 0.5999, 0.3107, 0.3223, 0.4715, 0.1537, 0.7373,
        0.7099, 0.6088, 0.1975, 0.1126, 0.4754, 0.9213, 0.0358, 0.3334, 0.8723,
        0.6762, 0.7247, 0.7627, 0.0828, 

In [60]:
viewed_tensor = flat_tensor.view(1, 28, 28)

In [61]:
viewed_tensor

tensor([[[0.8191, 0.9916, 0.5209, 0.2879, 0.0177, 0.2803, 0.4463, 0.6851,
          0.8156, 0.1780, 0.7343, 0.4050, 0.6385, 0.4054, 0.3816, 0.4684,
          0.8711, 0.2904, 0.5789, 0.1956, 0.1472, 0.9739, 0.6569, 0.1424,
          0.5602, 0.7926, 0.3876, 0.7309],
         [0.5363, 0.7460, 0.3407, 0.3454, 0.8003, 0.4253, 0.0520, 0.0832,
          0.0115, 0.0671, 0.4216, 0.5344, 0.4158, 0.5167, 0.4873, 0.1491,
          0.2955, 0.2971, 0.3039, 0.7933, 0.2146, 0.1115, 0.8082, 0.2362,
          0.2028, 0.4058, 0.0821, 0.0465],
         [0.1979, 0.1524, 0.8453, 0.0904, 0.1959, 0.5105, 0.3034, 0.5521,
          0.9853, 0.0066, 0.7204, 0.0786, 0.8199, 0.1880, 0.6227, 0.9084,
          0.6951, 0.6598, 0.0698, 0.1882, 0.0908, 0.8478, 0.0016, 0.9027,
          0.7384, 0.3312, 0.7310, 0.5466],
         [0.2224, 0.0580, 0.6250, 0.7266, 0.8384, 0.1095, 0.1944, 0.1168,
          0.9443, 0.5999, 0.3107, 0.3223, 0.4715, 0.1537, 0.7373, 0.7099,
          0.6088, 0.1975, 0.1126, 0.4754, 0.9213, 0.0358,

In [62]:
reshaped_tensor = flat_tensor.reshape(1, 28, 28)

In [63]:
reshaped_tensor

tensor([[[0.8191, 0.9916, 0.5209, 0.2879, 0.0177, 0.2803, 0.4463, 0.6851,
          0.8156, 0.1780, 0.7343, 0.4050, 0.6385, 0.4054, 0.3816, 0.4684,
          0.8711, 0.2904, 0.5789, 0.1956, 0.1472, 0.9739, 0.6569, 0.1424,
          0.5602, 0.7926, 0.3876, 0.7309],
         [0.5363, 0.7460, 0.3407, 0.3454, 0.8003, 0.4253, 0.0520, 0.0832,
          0.0115, 0.0671, 0.4216, 0.5344, 0.4158, 0.5167, 0.4873, 0.1491,
          0.2955, 0.2971, 0.3039, 0.7933, 0.2146, 0.1115, 0.8082, 0.2362,
          0.2028, 0.4058, 0.0821, 0.0465],
         [0.1979, 0.1524, 0.8453, 0.0904, 0.1959, 0.5105, 0.3034, 0.5521,
          0.9853, 0.0066, 0.7204, 0.0786, 0.8199, 0.1880, 0.6227, 0.9084,
          0.6951, 0.6598, 0.0698, 0.1882, 0.0908, 0.8478, 0.0016, 0.9027,
          0.7384, 0.3312, 0.7310, 0.5466],
         [0.2224, 0.0580, 0.6250, 0.7266, 0.8384, 0.1095, 0.1944, 0.1168,
          0.9443, 0.5999, 0.3107, 0.3223, 0.4715, 0.1537, 0.7373, 0.7099,
          0.6088, 0.1975, 0.1126, 0.4754, 0.9213, 0.0358,

In [65]:
reshaped_tensor.shape

torch.Size([1, 28, 28])

In [66]:
hwc_tensor = torch.rand(620, 345, 3)

In [67]:
chw_tensor = hwc_tensor.permute(2, 0 , 1)

In [69]:
chw_tensor.shape

torch.Size([3, 620, 345])